### ISSUE TITLE
CI/CD?

### ISSUE THREAD

**Issue by rugk** [tgbyte/docker-borg-backup#6]
For security reasons, you should automatically build and deliver updates e.g. when the Debian base image you depend on changes/in-cooperates security updates.

I guess, you should do this automatically in a CI/CD. I see no such one setup… so do you use one?

If so, where? If not, I'd strongly suggest that…

**Comment by rugk** [comment]
Ah there is a https://github.com/tgbyte/docker-borg-backup though I don't know/see what time/cron triggers are setup there.
And also, where is this on GitLab uhm? It seems GitHub is only a mirror then?

**Comment by ginkel** [comment]
Hi @rugk,

thanks for raising this issue. Builds are happening automatically in our private GitLab instance each time a new Borg version is released. New releases are checked for on a daily basis. There is currently no automatic procedure in place for security updates - I'd like to avoid creating a new image version per day with only dummy changes (due to non-reproducible Docker builds).

I could imagine doing periodic security scans using Trivy and triggering a build for the current version and `latest` in case vulnerabilities are detected.

What do you think about this approach?

Regards,
Thilo

-- 8< -- Edit -- 8< --

```
$ trivy debian:10         
2021-08-25T12:56:07.372+0200    INFO    Detected OS: debian
2021-08-25T12:56:07.372+0200    INFO    Detecting Debian vulnerabilities...
2021-08-25T12:56:07.388+0200    INFO    Number of language-specific files: 0

debian:10 (debian 10.10)
========================
Total: 112 (UNKNOWN: 0, LOW: 82, MEDIUM: 9, HIGH: 17, CRITICAL: 4)

[...]
```

So, apparently, Debian does not update their official Docker image on a regular basis. :-/ Debian 11 would help in this special case, but I'm not sure whether this is just an artifact of it being brand new.

I'll check whether Ubuntu LTS would be a better alternative.

**Comment by rugk** [comment]
> I could imagine doing periodic security scans using Trivy and triggering a build for the current version and latest in case vulnerabilities are detected.

For sure, that's better than nothing! :slightly_smiling_face:

**Comment by ginkel** [comment]
The automatic rebuild on fixed vulnerabilities is now in place and has published a new version of the image.
